# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 450)
        MainWindow.setMinimumSize(QtCore.QSize(320, 450))
        MainWindow.setMaximumSize(QtCore.QSize(400, 450))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"\n"
"border: 0px solid rgb(0, 0, 0);\n"
"\n"
"background-color: qlineargradient(spread:reflect, x1:0.516, y1:0, x2:0.513846, y2:1, stop:0 rgb(50, 150, 130,100%), stop:1 rgb(255, 255, 255));\n"
"\n"
"border-radius:20px;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 20, 128, 111))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 255, 255,0%);\n"
"border: None;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/gafas.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(116, 130, 101, 30))
        self.label_2.setStyleSheet("font: 75 14pt \" MS Shell Dlg 2\";\n"
"background-color: rgba(0,0,0,0%);\n"
"border:0px;")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(103, 230, 131, 31))
        self.label_3.setStyleSheet("font: 75 14pt \" MS Shell Dlg 2\";\n"
"background-color: rgba(0,0,0,0%);\n"
"border:0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.bt_ingresar = QtWidgets.QPushButton(self.frame)
        self.bt_ingresar.setGeometry(QtCore.QRect(85, 320, 171, 41))
        self.bt_ingresar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bt_ingresar.setStyleSheet("QPushButton{\n"
"\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #ffffff;\n"
"border-radius:20px;\n"
"background-color: rgb(50, 150, 130,60%);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/ingresar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_ingresar.setIcon(icon)
        self.bt_ingresar.setIconSize(QtCore.QSize(30, 30))
        self.bt_ingresar.setObjectName("bt_ingresar")
        self.users = QtWidgets.QLineEdit(self.frame)
        self.users.setGeometry(QtCore.QRect(43, 170, 241, 31))
        self.users.setStyleSheet("QLineEdit {\n"
"font: 75 12pt \"Arial\";\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"font: 75 12pt \"Arial\";\n"
"border-radius:10px;\n"
"background-color: rgb(50, 150, 130,7%);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.users.setText("")
        self.users.setAlignment(QtCore.Qt.AlignCenter)
        self.users.setObjectName("users")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(43, 260, 241, 31))
        self.password.setStyleSheet("QLineEdit {\n"
"font: 75 12pt \"Arial\";\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"    \n"
"\n"
"QLineEdit:hover {\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";\n"
"border-radius:10px;\n"
"background-color: rgb(50, 150, 130,5%);\n"
"}")
        self.password.setText("")
        self.password.setMaxLength(20)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.salir = QtWidgets.QPushButton(self.frame)
        self.salir.setGeometry(QtCore.QRect(127, 420, 75, 25))
        self.salir.setStyleSheet("\n"
"QPushButton{\n"
"border-radius:10px;\n"
"font: 75 10pt \" MS Shell Dlg 2\";\n"
"background-color: rgba(0, 0, 0,30%);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"    background-color: rgb(252, 14, 26,70%);\n"
"font: 75 10pt \" MS Shell Dlg 2\";;}")
        self.salir.setObjectName("salir")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(30, 380, 265, 20))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgba(0,0,0,0%);\n"
"border-radius:10px;\n"
"border: 0px solid #00007f;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"\n"
"background-color: qlineargradient(spread:reflect, x1:0.995263, y1:0.563, x2:0, y2:0.574, stop:0.301843 rgba(12, 185, 107), stop:1 white);\n"
"border-radius:10px;\n"
"border: 0px solid #00007f;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.usuario_incorrecto = QtWidgets.QLabel(self.frame)
        self.usuario_incorrecto.setGeometry(QtCore.QRect(95, 200, 150, 16))
        self.usuario_incorrecto.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border:0px;")
        self.usuario_incorrecto.setText("")
        self.usuario_incorrecto.setAlignment(QtCore.Qt.AlignCenter)
        self.usuario_incorrecto.setObjectName("usuario_incorrecto")
        self.contrasena_incorrecta = QtWidgets.QLabel(self.frame)
        self.contrasena_incorrecta.setGeometry(QtCore.QRect(95, 290, 150, 16))
        self.contrasena_incorrecta.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"border:0px;")
        self.contrasena_incorrecta.setText("")
        self.contrasena_incorrecta.setAlignment(QtCore.Qt.AlignCenter)
        self.contrasena_incorrecta.setObjectName("contrasena_incorrecta")
        self.cargando = QtWidgets.QLabel(self.frame)
        self.cargando.setGeometry(QtCore.QRect(90, 395, 155, 25))
        self.cargando.setStyleSheet("QLabel{\n"
"background-color: rgba(0,0,0,0%);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"border:0px;\n"
"}")
        self.cargando.setText("")
        self.cargando.setObjectName("cargando")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.salir.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "USUARIO"))
        self.label_3.setText(_translate("MainWindow", "CONTRASEÑA"))
        self.bt_ingresar.setText(_translate("MainWindow", "        INGRESAR     "))
        self.bt_ingresar.setShortcut(_translate("MainWindow", "Return"))
        self.users.setPlaceholderText(_translate("MainWindow", "ejemplo@opticacaroni.com"))
        self.password.setPlaceholderText(_translate("MainWindow", "Ingrese su contraseña"))
        self.salir.setText(_translate("MainWindow", "SALIR"))
        self.salir.setShortcut(_translate("MainWindow", "Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
